---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: secure-tomcat
  labels:
    app: secure-tomcat-app
    env: dev
spec:
  replicas: {{ .Values.replicacount }}  
  template:
    metadata:
      name: secure-tomcat
      labels: 
        app: secure-tomcat-app
        env: dev
    spec:
      containers:
      - name: secure-tomcat-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: tomcat-port
          containerPort: 8080


